# Stage 1: Build Stage
FROM node:18-alpine AS build

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --only=production

# Copy application code
COPY . .

# Stage 2: Production Stage
FROM node:18-alpine

# Set the working directory for the production image
WORKDIR /usr/src/app

# Copy only the necessary files from the build stage
COPY --from=build /usr/src/app .

# Expose the port that the app runs on
EXPOSE 3002

# Command to run the application
CMD ["node", "app.js"] 