version: "3.8"

services:
  user-service:
    build:
      context: ./user-service # Path to the User Service Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  product-service:
    build:
      context: ./product-service # Path to the Product Service Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network

  order-service:
    build:
      context: ./order-service # Path to the Order Service Dockerfile
    ports:
      - "3002:3002"
    networks:
      - app-network

  gateway-service:
    build:
      context: ./gateway-service # Path to the Gateway Service Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
